theme: jekyll-theme-minimal
title: julianolf
description: developer · gamer · human
social:
  -
    name: github
    url: https://github.com/julianolf
    icon: /assets/img/github.png
  -
    name: twitter
    url: https://twitter.com/julianolf
    icon: /assets/img/twitter.png
  -
    name: linkedin
    url: https://www.linkedin.com/in/julianolf
    icon: /assets/img/linkedin.png
